spring:
  profiles:
    group:
      default: common, redis, dev
---
spring:
  profiles:
    group:
      local: common

---
spring:
  config:
    activate:
      on-profile: common
  application:
    name: course
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: false

  datasource:
    url: "jdbc:mariadb://localhost:3306/course?rewriteBatchedStatements=true"
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 2
      maximum-pool-size: 5
      pool-name: course-domain-cp

  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9081

logging:
  level:
    root: info
    mz.course: debug

---
spring:
  config:
    activate:
      on-profile: redis
  session:
    store-type: redis
    timeout: 30m         # => 기본값 30분
  cache:
    type: redis

---
spring:
  config:
    activate:
      on-profile: dev
  redis:
    session:
      host: 127.0.0.1
      port: 6379
      password: redis1234
    cache:
      host: 127.0.0.1
      port: 6379
      password: redis1234
