spring:
  profiles:
    group:
      default: common, kafka

---
spring:
  profiles:
    group:
      local: common, non-kafka

---
spring:
  config:
    activate:
      on-profile: common
  application:
    name: academy
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: false

  datasource:
    url: "jdbc:mariadb://localhost:3306/academy?rewriteBatchedStatements=true"
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 2
      maximum-pool-size: 5
      pool-name: academy-domain-cp

  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    root: info
    mz.hr: debug

---
spring:
  config:
    activate:
      on-profile: kafka
  cloud:
    stream:
      bindings:
        accountRegistered:
          destination: account-registered-topic
---
spring:
  config:
    activate:
      on-profile: non-kafka
  autoconfigure:
    exclude:
      - org.springframework.cloud.stream.config.BindingServiceConfiguration
      - org.springframework.cloud.stream.function.FunctionConfiguration