spring:
  profiles:
    group:
      default: common, kafka
---
spring:
  profiles:
    group:
      local: common, non-kafka

---
spring:
  config:
    activate:
      on-profile: common
  application:
    name: usergate
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: false

  datasource:
    url: "jdbc:mariadb://localhost:3306/usergate?rewriteBatchedStatements=true"
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 2
      maximum-pool-size: 5
      pool-name: usergate-domain-cp

  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  messages:
    basename: message/messages
    encoding: UTF-8

server:
  port: 8088

logging:
  level:
    root: info
    mz.hr: debug

---
spring:
  config:
    activate:
      on-profile: kafka
  cloud:
    function:
      definition: accountRegistered;
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        accountRegistered-in-0:
          destination: account-registered-topic
          group: ${spring.application.name}Group

---
spring:
  config:
    activate:
      on-profile: non-kafka
  autoconfigure:
    exclude:
      - org.springframework.cloud.stream.config.BindingServiceConfiguration
      - org.springframework.cloud.stream.function.FunctionConfiguration

#---
#spring:
#  config:
#    activate:
#      on-profile: redis
#  session:
#    store-type: redis
#    timeout: 30m         # => 기본값 30분