spring:
  profiles:
    group:
      default: common

---
spring:
  config:
    activate:
      on-profile: common
  application:
    name: course-application
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: false

  datasource:
    url: "jdbc:mariadb://localhost:3306/course_application?rewriteBatchedStatements=true"
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 2
      maximum-pool-size: 5
      pool-name: course-application-domain-cp

  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

logging:
  level:
    root: info
    mz.hr: debug
